name: helm lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HELM_LINT_SARIF_FILE: "helm-lint-results.sarif"
  HELM_LINT_OUTPUT_FILE: "helm-lint-results.txt"
jobs:
  lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Run helm lint
        run: |
          set -o pipefail

          helm lint charts/mailpit | tee ${{ env.HELM_LINT_OUTPUT_FILE }}
          python3 helm_lint2sarif.py < ${{ env.HELM_LINT_OUTPUT_FILE }} > ${{ env.HELM_LINT_SARIF_FILE }}
      - name: upload helm lint results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: "${{ env.HELM_LINT_SARIF_FILE }}"
