name: trivy-code-scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TRIVY_SCAN_SARIF_FILE: "trivy-results.sarif"

jobs:
  scan:
    name: Trivy Code Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read          # Required to checkout and read repo files
      security-events: write  # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "config"
          format: "sarif"
          output: "${{ env.TRIVY_SCAN_SARIF_FILE }}"
          scan-ref: "."
          exit-code: '1'
          severity: "CRITICAL,HIGH"

      - name: upload trivy results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: "${{ env.TRIVY_SCAN_SARIF_FILE }}"
